<div id="OasDocs"class="container-fluid">
    <div class="row">
        <div class="col-md-12">
            <h1><?= $this->params['title'] ?></h1>
        </div>
        <div id="docsLeft" class="col-md-3">
            <?= $this->render('_toc', ['toc' => $toc]) ?>
        </div>
        <div id="docsRight" class="col-md-9">
            <?php if ($partial) : ?>
                <?= $this->render(
                    $partial,
                    [
                        'data' => $data,
                        'id' => $id,
                        'section' => $toc->currentSection()
                    ]
                ) ?>
            <?php endif ?>
        </div>
    </div>
    <div id="footer" class="row">
        <div class="col-md-12 text-center">
            <hr/>
            <a href='<?= $this->context->getDownloadLink() ?>'>Download schema</a> | Generated by <a href=''>danballance/yii2-oas-docs</a>
        </div>
    </div>
</div>
